### PR TITLE
std::lock_guard<std::mutex> lock(this->connectionListMutex);

### LINKED ISSUE #2: Crash when using `ovos-speak`
```
$ ovos-speak "Hello world"
2023-06-08 11:34:57.386 - OVOS - ovos_bus_client.session:reset_default_session:225 - INFO - New Default Session Start: d64a1ad3-8ae6-4a08-a160-afaf39e1aa03
```

```
Connection opened.
There are now 18 open connections.
[2023-06-08 11:34:57] [connect] WebSocket Connection [::ffff:127.0.0.1]:44224 v13 "" /core 101
[2023-06-08 11:34:57] [control] Control frame received with opcode 8
message handler on the main thread
Message payload:
{"context":{"session":{"active_skills":[],"context":{"frame_stack":[],"timeout":101174309760},"history":[[{"context":{},"data":{"lang":"fr-fr","utterance":"Hello world"},"type":"speak"},1686238497.3873408]],"lang":"fr-fr","session_id":"d64a1ad3-8ae6-4a08-a160-afaf39e1aa03","utterance_states":{},"valid_languages":["fr-fr"]}},"data":{"lang":"fr-fr","utterance":"Hello world"},"type":"speak"}
[2023-06-08 11:34:57] [frame_header] Dispatching write containing 1 message(s) containing 2 header bytes and 2 payload bytes
[2023-06-08 11:34:57] [frame_header] Header Bytes: 
[0] (2) 88 02 

[2023-06-08 11:34:57] [frame_payload] Payload Bytes: 
[0] (2) [8] 03 E8 

terminate called after throwing an instance of 'websocketpp::exception'
  what():  invalid state
Aborted
```

### PR DESCRIPTION
**Pull request by JarbasAl**
maybe fixes #2 / #3

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved thread safety for message handling in the WebSocket server, ensuring more reliable and stable operations.

### CODE REVIEW

**Comment by builderjer** [comment]
I am testing this on the latest raspOVOS headless image.  

Stopped the original messagebus, and started up this one.  It has been running for about 10 minutes, asking things with voice, ovos-say-to and ovos-simple-cli

Seems to be working for now

**Comment by goldyfruit** [comment]
Does not work for me.

image

**Comment by builderjer** [comment]
works starting it from the command line.  need to make a systemd service for it.  replacing the command in the existing one does not work

**Comment by builderjer** [comment]
> Does not work for me.
> 
Maybe a docker difference? It is working fine if I start it from the command line

**Comment by builderjer** [comment]
strange.  Changed the systemd service from `notify` to `simple`.

it said it failed to start, but seems to be running when I `ps` it.  And is working for me also

**Comment by goldyfruit** [comment]
> > Does not work for me.
> 
> Maybe a docker difference? It is working fine if I start it from the command line

Bus is not running in a container during my tests.

**Comment by builderjer** [comment]
My systemd service is showing failed,  but it is running, all skills work and everything

**Review by goldyfruit — COMMENTED** [review]
Still having the this error:
```
terminate called without an active exception
```

**Comment by goldyfruit** [comment]
Even with only one connection on the bus it crashes, the first one works _(not always)_ but then the second one crashes the server.

```
[2024-01-03 10:35:45] [connect] WebSocket Connection [::ffff:127.0.0.1]:59484 v13 "" /core 101
Connection opened.
There are now 1 open connections.
message handler on the main thread
Message payload:
[2024-01-03 10:35:45] [control] Control frame received with opcode 8
{"context":{"session":{"active_skills":[],"context":{"frame_stack":[],"timeout":120},"lang":"en-us","pipeline":["converse","padatious_high","adapt","common_qa","fallback_high","padatious_medium","fallback_medium","padatious_low","fallback_low"],"session_id":"default","site_id":"unknown","stt":{"config":{},"plugin_id":"ovos-stt-plugin-server"},"tts":{"config":{"voice":"ryan-high"},"plugin_id":"ovos-tts-plugin-server"},"utterance_states":{}}},"data":{},"type":"ovos.session.sync"}
[2024-01-03 10:35:45] [frame_header] Dispatching write containing 1 message(s) containing 2 header bytes and 2 payload bytes
[2024-01-03 10:35:45] [frame_header] Header Bytes: 
[0] (2) 88 02 

[2024-01-03 10:35:45] [frame_payload] Payload Bytes: 
[0] (2) [8] 03 E8 

[2024-01-03 10:35:45] [disconnect] Disconnect close local:[1000] remote:[1000]
message handler on the main thread
Message payload:
{"context":{"session":{"active_skills":[],"context":{"frame_stack":[],"timeout":120},"lang":"en-us","pipeline":["converse","padatious_high","adapt","common_qa","fallback_high","padatious_medium","fallback_medium","padatious_low","fallback_low"],"session_id":"default","site_id":"unknown","stt":{"config":{},"plugin_id":"ovos-stt-plugin-server"},"tts":{"config":{"voice":"ryan-high"},"plugin_id":"ovos-tts-plugin-server"},"utterance_states":{}}},"data":{"lang":"en-us","utterances":["how are you"]},"type":"recognizer_loop:utterance"}
Connection closed.
There are now 0 open connections.
[2024-01-03 10:35:48] [connect] WebSocket Connection [::ffff:127.0.0.1]:59496 v13 "" /core 101
Connection opened.
There are now 1 open connections.
[2024-01-03 10:35:48] [control] Control frame received with opcode 8
message handler on the main thread[2024-01-03 10:35:48] [frame_header] Dispatching write containing 1 message(s) containing 2 header bytes and 2 payload bytes
[2024-01-03 10:35:48] [frame_header] Header Bytes: 
[0] (2) 88 02 

[2024-01-03 10:35:48] [frame_payload] Payload Bytes: 
[0] (2) [8] 03 E8 


Message payload:
{"context":{"session":{"active_skills":[],"context":{"frame_stack":[],"timeout":120},"lang":"en-us","pipeline":["converse","padatious_high","adapt","common_qa","fallback_high","padatious_medium","fallback_medium","padatious_low","fallback_low"],"session_id":"default","site_id":"unknown","stt":{"config":{},"plugin_id":"ovos-stt-plugin-server"},"tts":{"config":{"voice":"ryan-high"},"plugin_id":"ovos-tts-plugin-server"},"utterance_states":{}}},"data":{"lang":"en-us","utterances":["how are you"]},"type":"recognizer_loop:utterance"}
terminate called after throwing an instance of 'websocketpp::exception'
  what():  invalid state
fish: Job 1, './ovos-bus-server' terminated by signal SIGABRT (Abort)
```

**Comment by goldyfruit** [comment]
Maybe the solution will be one thread per connection and detach from it, that way the main thread will not get crashed.

**Comment by JarbasAl** [comment]
@coderabbitai review

**Comment by JarbasAl** [comment]
@coderabbitai review

**Pull request closed without merging**
